# when docker build frontend alone

# FROM oven/bun:1 AS builder

# WORKDIR /app

# # Copy root files
# COPY package.json bun.lock turbo.json ./

# # Copy ONLY web app (important)
# COPY apps/web ./apps/web

# # Move to web app
# WORKDIR /app/apps/web

# # Install ONLY web dependencies
# RUN bun install

# # Build
# RUN bun run build

# # ---------- 2️⃣ Production Stage ----------
# FROM oven/bun:1 AS runner

# WORKDIR /app

# # Copy only built app (NOT full source)
# # Copy built app
# COPY --from=builder /app/apps/web/.next ./.next
# COPY --from=builder /app/apps/web/public ./public
# COPY --from=builder /app/apps/web/package.json ./package.json
# COPY --from=builder /app/apps/web/node_modules ./node_modules

# # Expose port
# EXPOSE 3000

# # Start production server
# CMD ["bunx", "next", "start"]

# with docker-compose up

FROM oven/bun:1 AS builder

WORKDIR /app

RUN bun add -g turbo

COPY . .

RUN turbo prune web --docker

WORKDIR /app/out/full

ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ENV NEXT_DISABLE_TURBOPACK=1

RUN bun install --frozen-lockfile
RUN bun run build


# ---------- Production ----------
FROM oven/bun:1 AS runner

WORKDIR /app

COPY --from=builder /app/out/full/apps/web/.next/standalone ./
COPY --from=builder /app/out/full/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/out/full/apps/web/public ./apps/web/public

EXPOSE 3000

CMD ["server.js"]